# Imports

In [26]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

from ydata_profiling import ProfileReport
import warnings
warnings.filterwarnings('ignore')

# Dataset

In [2]:
df = pd.read_csv("data/stud.csv")

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

# Obervation:
No null values <br>
we can just handle the categorical Features

# Feature Engineering

In [8]:
df['total_score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['average']=df['total_score']/3

In [9]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [17]:
math_full=df[df['math_score'] == 100]['average'].count()
read_full=df[df['reading_score'] >= 80]['average'].count()
write_full=df[df['writing_score'] >= 80]['average'].count()

print('The student who got the full reading_score',read_full)
print('The student who got the full write_score',write_full)
print('The student who got the full math_score',math_full)

The student who got the full reading_score 249
The student who got the full write_score 235
The student who got the full math_score 7

# handling the Categorical Features

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
 8   total_score                  1000 non-null   int64
 9   average                      1000 non-null   float64
dtypes: float64(1), int64(4), object(5)
memory usage: 78.3+ KB

In [19]:
LabelEncoder = LabelEncoder()
df['gender'] = LabelEncoder.fit_transform(df['gender'])
df['race_ethnicity'] = LabelEncoder.fit_transform(df['race_ethnicity'])
df['parental_level_of_education'] = LabelEncoder.fit_transform(df['parental_level_of_education'])
df['lunch'] = LabelEncoder.fit_transform(df['lunch'])
df['test_preparation_course'] = LabelEncoder.fit_transform(df['test_preparation_course'])

In [20]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,0,1,1,1,1,72,72,74,218,72.666667
1,0,2,4,1,0,69,90,88,247,82.333333
2,0,1,3,1,1,90,95,93,278,92.666667
3,1,0,0,0,1,47,57,44,148,49.333333
4,1,2,4,1,1,76,78,75,229,76.333333

# feature Selection

In [21]:
x = df.drop(['total_score','math_score','reading_score','writing_score'],axis=1)
y = df.drop('total_score', axis=1)

In [24]:
feature_sel_model = SelectFromModel(Lasso(alpha=0.005, random_state=42))
feature_sel_model.fit(x, y)

SelectFromModel(estimator=Lasso(alpha=0.005, random_state=42))

In [25]:
feature_sel_model.get_support()

array([ True,  True,  True,  True,  True,  True])

# Observation:
All Features are necessary

# Automated Visualization

In [28]:
profile = ProfileReport(df, explorative=True)

In [29]:
profile.to_file('report.html')

100%|██████████| 10/10 [00:00<00:00, 83.60it/s]<00:00, 34.10it/s, Describe variable: average]
Summarize dataset: 100%|██████████| 55/55 [00:06<00:00,  8.21it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.36s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 29.27it/s]